/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BlogMainPost: typeof import('./src/components/PostList.vue')['default']
    BlogSidebar: typeof import('./src/components/layouts/BlogSidebar.vue')['default']
    CommentComponent: typeof import('./src/components/CommentComponent.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    FloatingContactButton: typeof import('./src/components/layouts/FloatingContactButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/layouts/NavBar.vue')['default']
    PostForm: typeof import('./src/components/post/PostForm.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PublishModal: typeof import('./src/components/PublishModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TagInput: typeof import('./src/components/tag/TagInput.vue')['default']
    ToastEditor: typeof import('./src/components/editor/ToastEditor.vue')['default']
    TopPostInCategory: typeof import('./src/components/TopPostInCategory.vue')['default']
    TuiEditorWithTagify: typeof import('./src/components/TuiEditorWithTagify.vue')['default']
    UserTerminal: typeof import('./src/components/UserTerminal.vue')['default']
  }
}
