/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogSidebar: typeof import('./src/components/layouts/BlogSidebar.vue')['default']
    FloatingContactButton: typeof import('./src/components/layouts/FloatingContactButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/layouts/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserTerminal: typeof import('./src/components/UserTerminal.vue')['default']
  }
}
