/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/blog/BlogMain': RouteRecordInfo<'/blog/BlogMain', '/blog/BlogMain', Record<never, never>, Record<never, never>>,
    '/blog/BlogSetting': RouteRecordInfo<'/blog/BlogSetting', '/blog/BlogSetting', Record<never, never>, Record<never, never>>,
    '/blog/PostView': RouteRecordInfo<'/blog/PostView', '/blog/PostView', Record<never, never>, Record<never, never>>,
    '/blog/Write': RouteRecordInfo<'/blog/Write', '/blog/Write', Record<never, never>, Record<never, never>>,
    '/login/success': RouteRecordInfo<'/login/success', '/login/success', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/onboarding': RouteRecordInfo<'/onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    '/Signup': RouteRecordInfo<'/Signup', '/Signup', Record<never, never>, Record<never, never>>,
  }
}
