spring:
  servlet:
    multipart:
      enabled: true  # 멀티파트 파일 업로드 활성화
      max-file-size: 10MB  # 개별 파일 최대 크기 (10MB)
      max-request-size: 50MB  # 전체 요청 크기 제한 (여러 파일 포함 가능, 최대 50MB)

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100  # 여러 개의 데이터를 한 번에 조회할 때 Batch 크기 설정 (성능 최적화)

server:
  tomcat:
    uri-encoding: utf-8  # Tomcat 서버의 URI 인코딩을 UTF-8로 설정 (한글, 특수문자 인코딩 문제 방지)
  servlet:
    encoding:
      charset: UTF-8  # 서버의 기본 문자 인코딩을 UTF-8로 설정

management:
  info:
    java:
      enabled: true  # `/actuator/info` 엔드포인트에서 Java 정보 제공 (JVM 버전 등)
    os:
      enabled: true  # `/actuator/info`에서 OS 관련 정보 제공 (OS 이름, 버전 등)
    env:
      enabled: true  # `/actuator/info`에서 환경 변수 정보 제공

  endpoint:
    shutdown:
      access: none  # `/actuator/shutdown` 엔드포인트를 비활성화 (안전성 확보)
    health:
      show-details: always  # `/actuator/health` 엔드포인트에서 자세한 시스템 상태 정보 제공

  endpoints:
    web:
      exposure:
        include: "*"  # 모든 Actuator 엔드포인트를 외부에서 접근 가능하도록 허용
