spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
#  web:
#    resources:
#      static-locations: classpath:/static/, file:/upload/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  # 위는 개발용 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/notej
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100


logging:
  level:
    org:
      hibernate:
        SQL: info
        orm:
          jdbc:
            bind: info
      springframework:
        web: INFO

file:
  dir: ${fileDir:/Users/piehealthcare/Documents/private/noteJ-storage/}

server:
  port: 8080
  serverAddress: localhost
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8

cloud:
  aws:
    credentials:
      access-key: localNoKey
      secret-key: localSecretNoKey
    region:
      static: localNoRegion
    s3:
      bucket: localNoBucket

serverName: local_server



---

spring:
  config:
    activate:
      on-profile: blue
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_NAME}?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # 커넥션 풀 크기 설정 (필요시 조정)
      connection-timeout: 30000 # 연결 대기 시간 설정
      idle-timeout: 600000 # 유휴 연결 시간 설정
      max-lifetime: 1800000 # 연결 최대 수명 설정
    # 기타 JDBC 설정을 추가할 수 있습니다.
  jpa:
    hibernate:
      ddl-auto: create # 자동 테이블 생성 비활성화 (Flyway 또는 Liquibase를 사용할 경우)
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#      flyway:
#        enabled: true
#        locations: classpath:db/migration
#        baseline-on-migrate: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

server:
  port: 8080
  serverAddress: ${LIVE_SERVER_IP}
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_NAME}?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # 커넥션 풀 크기 설정 (필요시 조정)
      connection-timeout: 30000 # 연결 대기 시간 설정
      idle-timeout: 600000 # 유휴 연결 시간 설정
      max-lifetime: 1800000 # 연결 최대 수명 설정
    # 기타 JDBC 설정을 추가할 수 있습니다.
  jpa:
    hibernate:
      ddl-auto: create # 자동 테이블 생성 비활성화 (Flyway 또는 Liquibase를 사용할 경우)
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#      flyway:
#        enabled: true
#        locations: classpath:db/migration
#        baseline-on-migrate: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

server:
  port: 8081
  serverAddress: ${LIVE_SERVER_IP}
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8

serverName: green_server

---
